# Generated by Django 5.0.7 on 2024-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empID', models.CharField(max_length=70, unique=True)),
                ('empName', models.CharField(max_length=60)),
                ('empDesg', models.CharField(max_length=70)),
                ('empSlaray', models.IntegerField()),
            ],
        ),
    ]
